#!/bin/bash

# 2022-06-19

shfile=$0
shdir=$(realpath "$(dirname "${shfile}")")
cwd=$shdir

echo "shfile =>  $0"
echo "shdir  =>  ${shdir}"
echo "cwd    =>  ${cwd}"

i=1; for arg in "$@"; do
  echo "arg[${i}] =>  ${arg}"
  i=$((i + 1))
done

exe=${cwd}/client

count=10; [ -n "$1" ] && count="$1"

for ((i=1; i <= count; i++)); do
  echo ""
  echo "#${i} ..."
  ${exe}
done
