#!/bin/bash

################################################################################
shfile=$0
shdir=$(realpath "$(dirname "${shfile}")")
cwd=$shdir

echo "shfile =>  $0"
echo "shdir  =>  ${shdir}"
echo "cwd    =>  ${cwd}"

# args
i=1; for arg in "$@"; do
  echo "arg[${i}] =>  ${arg}"
  i=$((i + 1))
done
################################################################################

# bin
bin=${cwd}/bin/$(uname)
if [ -e ${bin} ]; then
  rm -vrf ${bin}
fi
mkdir -vp ${bin}

# server
server=${bin}/echo_c_tcp_server
clang -std=c11 -Wall ${cwd}/server.c ${cwd}/../utils/log.c -o ${server}
file ${server}

# server6
server6=${bin}/echo_c_tcp_server6
clang -std=c11 -Wall ${cwd}/server6.c ${cwd}/../utils/log.c -o ${server6}
file ${server6}

# client
client=${bin}/echo_c_tcp_client
clang -std=c11 -Wall ${cwd}/client.c ${cwd}/../utils/log.c -o ${client}
file ${client}

# client6
client6=${bin}/echo_c_tcp_client6
clang -std=c11 -Wall ${cwd}/client6.c ${cwd}/../utils/log.c -o ${client6}
file ${client6}
