#!/bin/bash

# 2022-06-18

shfile=$0
shdir=$(realpath "$(dirname "${shfile}")")
cwd=$shdir

echo "shfile =>  $0"
echo "shdir  =>  ${shdir}"
echo "cwd    =>  ${cwd}"

i=1; for arg in "$@"; do
  echo "arg[${i}] =>  ${arg}"
  i=$((i + 1))
done

tmpfile=$(mktemp -u)
tmpdir=$(dirname "${tmpfile}")
sockdir=${tmpdir}/gypsy.toy.echo.sock
if [ -e "${sockdir}" ]; then
  rm -vrf "${sockdir}"
fi
