#!/bin/bash

# 2022-06-18

################################################################################
shfile=$0
shdir=$(realpath "$(dirname "${shfile}")")
cwd=$shdir

echo "shfile =>  $0"
echo "shdir  =>  ${shdir}"
echo "cwd    =>  ${cwd}"

# args
i=1; for arg in "$@"; do
  echo "arg[${i}] =>  ${arg}"
  i=$((i + 1))
done
################################################################################

using_ipv6=undef
using_ipv6_prefix=--x-using-ipv6=
for arg in "$@"; do
  echo "arg =>  ${arg}"
  case "${arg}" in
    "${using_ipv6_prefix}"*)
      using_ipv6=${arg:${#using_ipv6_prefix}}
      ;;
    *)
      break
      ;;
  esac
done
echo "using_ipv6  =>  [${using_ipv6}]"


if [[ "yes" = "${using_ipv6}" ]]; then
  ipv6_suffix="_ipv6"
else
  ipv6_suffix=""
fi

bin=${cwd}/bin/$(uname)
exe=${bin}/echo_c_tcp_client${ipv6_suffix}

if [ "$#" -gt "1" ]; then
  ${exe} "$@"
else
  ${exe} "--ip=127.0.0.1" "--port=9999" "--data=hello.$(date +%s)"
fi
